### ISSUE TITLE
async listening?

### ISSUE THREAD

**Issue by gutbash** [imayhaveborkedit/discord-ext-voice-recv#11]
?

**Comment by imayhaveborkedit** [comment]
?

**Comment by ThatOtherAndrew** [comment]
?

**Comment by gutbash** [comment]
how do i make the on_message handler async? i need to do some async stuff in there

**Comment by imayhaveborkedit** [comment]
This extension doesn't add anything called "on_message".  Refer to the readme.  Everything is listed there.  If you need to use something async in a sync function, use one of the usual asyncio mechanisms for it, like `run_coroutine_threadsafe`.

**Comment by gutbash** [comment]
oh sorry how about AudioSink.listener()? just use asyncio mechanism?

**Comment by imayhaveborkedit** [comment]
https://docs.python.org/3/library/asyncio-task.html#scheduling-from-other-threads
