### ISSUE TITLE
Question: Receive and Send Video

### ISSUE THREAD

**Issue by guidevops** [imayhaveborkedit/discord-ext-voice-recv#13]
Do you know if discord supports the bot sending or receiving image/video during the call ?

I used this library to integrate a voice interface into my AI assistant, I would like to be able to send and receive video/images, so I could share my screen so the AI has context of what I'm doing and if the bot can send videos, the AI will have a channel to be able to transmit whatever it wants, such as the image of a browser or vm that it is controlling.

**Comment by imayhaveborkedit** [comment]
Bots can't use video and it would be too complicated to reverse engineer and resource intensive to do feasibly anyway.  If you want to do that you just need a second account to stream and have the bot control what's displayed on the computer.
