### ISSUE TITLE
Question: Wit Key?

### ISSUE THREAD

**Issue by VenusMods** [imayhaveborkedit/discord-ext-voice-recv#14]
Hi, i'm trying to use wit as the default_recognizer like this:
`vc = await ctx.author.voice.channel.connect(cls=voice_recv.VoiceRecvClient)
vc.listen(voice_recv.extras.SpeechRecognitionSink(default_recognizer="wit"))`
But getting a TypeError with recognize_wit() missing the key. 
I have the key, but have no idea how to pass it into the sink, I checked the source code in speechrecognition.py and it doesn't look like there's any code to accept a key, maybe i'm just dumb. Any help would be appreciated, as the only one I can currently use is the default "google" one.

**Comment by imayhaveborkedit** [comment]
You have to provide a `process_cb` parameter where you call the function with the args you need.
https://github.com/imayhaveborkedit/discord-ext-voice-recv/blob/3398a4d9d2f646cfcd60f68e626cd750b759893f/discord/ext/voice_recv/extras/speechrecognition.py#L130

See this for reference.  I'm probably going to add something to pass kwargs directly to that function at some point.

**Comment by VenusMods** [comment]
> You have to provide a `process_cb` parameter where you call the function with the args you need.
> 
> https://github.com/imayhaveborkedit/discord-ext-voice-recv/blob/3398a4d9d2f646cfcd60f68e626cd750b759893f/discord/ext/voice_recv/extras/speechrecognition.py#L130-L141
> 
> See this for reference. I'm probably going to add something to pass kwargs directly to that function at some point.

Not exactly sure what you mean, I tried:
`def process_wit(recognizer, audio, user):`
`            text = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ### wit_api_key`
`            return text`
`vc = await ctx.author.voice.channel.connect(cls=voice_recv.VoiceRecvClient)
vc.listen(voice_recv.extras.SpeechRecognitionSink(process_cb=process_wit, default_recognizer="wit"))`
but it just outputs this:
`discord.ext.voice_recv.extras.speechrecognition conkhi27 said: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

**Comment by imayhaveborkedit** [comment]
The `process_cb` callback overrides the default process function, shown in the code.  Basically it just calls the speechrecognition `recognize_x` function and returns the result.  Your code needs to do that and call the `recognize_wit` function with the api key, not return it.

**Comment by VenusMods** [comment]
> The `process_cb` callback overrides the default process function, shown in the code. Basically it just calls the speechrecognition `recognize_x` function and returns the result. Your code needs to do that and call the `recognize_wit` function with the api key, not return it.

        `def process_wit(recognizer: sr.Recognizer, audio: sr.AudioData, user):
            self.default_recognizer = "wit"

            func = getattr(recognizer, 'recognize_' + self.default_recognizer, recognizer.recognize_google)
            text = func(audio, key=wit_api_key)


        vc = await ctx.author.voice.channel.connect(cls=voice_recv.VoiceRecvClient)
        vc.listen(voice_recv.extras.SpeechRecognitionSink(process_cb=process_wit))`

I'm pretty sure that's what you mean, but I keep getting this:
`speech_recognition.exceptions.UnknownValueError`

**Comment by VenusMods** [comment]
> > The `process_cb` callback overrides the default process function, shown in the code. Basically it just calls the speechrecognition `recognize_x` function and returns the result. Your code needs to do that and call the `recognize_wit` function with the api key, not return it.
> 
> ```
>     `def process_wit(recognizer: sr.Recognizer, audio: sr.AudioData, user):
>         self.default_recognizer = "wit"
> 
>         func = getattr(recognizer, 'recognize_' + self.default_recognizer, recognizer.recognize_google)
>         text = func(audio, key=wit_api_key)
> 
> 
>     vc = await ctx.author.voice.channel.connect(cls=voice_recv.VoiceRecvClient)
>     vc.listen(voice_recv.extras.SpeechRecognitionSink(process_cb=process_wit))`
> ```
> 
> I'm pretty sure that's what you mean, but I keep getting this: `speech_recognition.exceptions.UnknownValueError`

I got it to work with this:
`def process_wit(recognizer: sr.Recognizer, audio: sr.AudioData, user: Optional[str]) -> Optional[str]:
            text: Optional[str] = None

            try:
                func = getattr(recognizer, 'recognize_wit', recognizer.recognize_google)
                text = func(audio, key=wit_api_key)
            except sr.UnknownValueError:
                print("Bad speech chunk")

            return text


        vc = await ctx.author.voice.channel.connect(cls=voice_recv.VoiceRecvClient)
        vc.listen(voice_recv.extras.SpeechRecognitionSink(process_cb=process_wit, default_recognizer="wit"))`
it finally started printing speech to text, although there were a lot of "bad speech chunks" during the silences. Seems like it's working now though

**Comment by VenusMods** [comment]
Also got this after like a minute:
speech_recognition.exceptions.RequestError: recognition request failed: Too Many Requests

**Comment by sayborduu** [comment]
> Also got this after like a minute: speech_recognition.exceptions.RequestError: recognition request failed: Too Many Requests

You could try hosting Vosk and using it as the recognizer
