### ISSUE TITLE
SpeechRecognitionSink Fetch User Name?

### ISSUE THREAD

**Issue by VenusMods** [imayhaveborkedit/discord-ext-voice-recv#17]
I have this code:
`func = getattr(recognizer, 'recognize_google', recognizer.recognize_google)`
`text = func(audio)`
`print(text)`
which outputs:
`it was such a unique thing`
`2024-05-12 19:17:49 INFO     discord.ext.voice_recv.extras.speechrecognition sxypotatoe said: it was such a unique thing`
I'm able to print the text that is said ("it was such a unique thing"), but how do I grab the name that said it, ie "sxypotatoe" here?

**Comment by VenusMods** [comment]
nvm I get it through user.display_name

**Comment by Marcusbjol** [comment]
close the issue if you found it
