### ISSUE TITLE
Byte Streaming

### ISSUE THREAD

**Issue by NoahCxrest** [imayhaveborkedit/discord-ext-voice-recv#3]
How could i get a byte stream in pcm format for every speaker in the vc without waiting for the person to stop speaking? Discord.js has implementation of this, but it doesn’t appear this does.
https://github.com/chebro/discord-voice-recorder

**Comment by imayhaveborkedit** [comment]
If the raw pcm packets is all you want you just need a `BasicSink` with whatever your callback is.
```py
def cb(member, data):
   ... # do whatever with data.pcm

sink = voice_recv.BasicSink(cb) 
```

**Comment by NoahCxrest** [comment]
> If the raw pcm packets is all you want you just need a `BasicSink` with whatever your callback is.
> 
> ```python
> def cb(member, data):
>    ... # do whatever with data.pcm
> 
> sink = voice_recv.BasicSink(cb) 
> ```

Thanks for the quick reply, borked.
I’m more of a Go/C# guy, so this may be a stupid question; but what triggers the callback?

**Comment by imayhaveborkedit** [comment]
Receiving a packet does.  When packets come in, the callback gets called.  I don't know what you expected.

**Comment by NoahCxrest** [comment]
Thanks. This library is a true lifesaver! Have a good weekend :)

**Comment by NoahCxrest** [comment]
Thanks. This library is a true lifesaver! Have a good weekend :)
