### ISSUE TITLE
Synchronous code with opus.py

### ISSUE THREAD

**Issue by NoahCxrest** [imayhaveborkedit/discord-ext-voice-recv#4]
Why is almost all of opus.py synchronous? I can't have asynchronous code inside of my project for some things just because of this.

**Comment by imayhaveborkedit** [comment]
For the same reason that all of the voice send code in discord.py is sync.  You'll notice that `AudopPlayer.read()` is sync and the `play()` `after` callback is sync.  It has to be sync.  The voice code is very dependent on performance, and can't afford to be integrated with the async loop.  In fact, there's no reason for it to be async, as it adds nothing to the code flow.  If you need to use async functions in sync functions from another thread, just use the standard asyncio mechanisms for doing that.  See: https://docs.python.org/3/library/asyncio-task.html#scheduling-from-other-threads
